name: Build docker images (Past CI)

on:
  push:
    branches:
      - enable_backward_forward_ci

concurrency:
  group: docker-images-builds
  cancel-in-progress: false

jobs:
  past-pytorch-docker:
    name: "Past PyTorch Docker"
    strategy:
      fail-fast: false
      matrix:
        version: ["1.13", "1.12"]
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Check out code
        uses: actions/checkout@v3
      -
        id: get-base-image
        name: Get Base Image
        env:
          framework_version: ${{ matrix.version }}
        run: |
          echo "base_image=$(python3 -c 'import os; from utils.past_ci_versions import past_versions_testing; base_image = past_versions_testing["pytorch"][os.environ["framework_version"]]["base_image"]; print(base_image)')" >> $GITHUB_OUTPUT
      -
        name: Print Base Image
        run: |
          echo ${{ steps.get-base-image.outputs.base_image }}
